import sys
import os
import requests
import base64
import ast
from datetime import datetime

base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
sys.path.insert(0, os.path.join(base_dir, 'apps', 'aipcsr-api'))
sys.path.insert(0, os.path.join(base_dir, 'core', 'db-core'))

from celery import shared_task

@shared_task(bind=True)
def apply_patch(self, vuln_id: str):
    """Clone repo, apply AI patch, commit, push, and open PR via GitHub API"""
    from session import SessionLocal
    from app.models.vulnerability import Vulnerability
    from app.models.report import Report
    from app.models.scan import Scan
    from app.models.repository import Repository
    from app.models.user import User

    db = SessionLocal()
    try:
        self.update_state(state='PROGRESS', meta={'status': 'applying_patch'})
        
        vuln = db.query(Vulnerability).filter(Vulnerability.id == vuln_id).first()
        if not vuln or not vuln.ai_patch_code:
            raise Exception("Vulnerability or patch code not found")

        report = db.query(Report).filter(Report.id == vuln.report_id).first()
        scan = db.query(Scan).filter(Scan.id == report.scan_id).first()
        repo = db.query(Repository).filter(Repository.id == scan.repository_id).first()
        user = db.query(User).filter(User.id == repo.owner_id).first()

        if not user.github_token:
            raise Exception("User has no GitHub token configured for pushing")
            
        # Parse Repo Owner and Name
        repo_url = repo.url.rstrip("/")
        if "github.com/" not in repo_url:
            raise Exception("Only GitHub repositories are supported")
        
        repo_full_name = repo_url.split("github.com/")[1] # e.g. owner/repo
        
        headers = {
            "Authorization": f"Bearer {user.github_token}",
            "Accept": "application/vnd.github.v3+json",
            "X-GitHub-Api-Version": "2022-11-28"
        }
        api_base = f"https://api.github.com/repos/{repo_full_name}"
        
        # 1. Get default branch
        repo_info = requests.get(api_base, headers=headers)
        repo_info.raise_for_status()
        default_branch = repo_info.json().get("default_branch", "main")
        
        # 2. Get latest commit SHA of default branch
        ref_info = requests.get(f"{api_base}/git/ref/heads/{default_branch}", headers=headers)
        ref_info.raise_for_status()
        base_sha = ref_info.json()["object"]["sha"]
        
        # 3. Create a new branch
        new_branch_name = f"sentinelai-patch-{vuln_id[:8]}"
        create_branch_res = requests.post(
            f"{api_base}/git/refs",
            headers=headers,
            json={"ref": f"refs/heads/{new_branch_name}", "sha": base_sha}
        )
        if create_branch_res.status_code != 201 and "already exists" not in create_branch_res.text:
            create_branch_res.raise_for_status()
            
        # 4. Get the file contents
        file_res = requests.get(f"{api_base}/contents/{vuln.file_path}?ref={new_branch_name}", headers=headers)
        file_res.raise_for_status()
        file_data = file_res.json()
        file_sha = file_data["sha"]
        
        content_decoded = base64.b64decode(file_data["content"]).decode('utf-8')
        lines = content_decoded.split('\n')
        
        # Extract the AI fix
        try:
            patch_dict = ast.literal_eval(vuln.ai_patch_code)
            fix_code = patch_dict.get("fix", "/* Auto-generated fix applied here */")
        except:
            fix_code = vuln.ai_patch_code
            
        # Apply the fix (best effort: replace the specific line or append)
        target_line = vuln.line_number
        if target_line and 1 <= target_line <= len(lines):
            lines[target_line - 1] = fix_code
        else:
            lines.append(f"\n# SentinelAI Fix:\n{fix_code}")
            
        new_content = '\n'.join(lines)
        new_content_encoded = base64.b64encode(new_content.encode('utf-8')).decode('utf-8')
        
        # 5. Commit the updated file
        update_res = requests.put(
            f"{api_base}/contents/{vuln.file_path}",
            headers=headers,
            json={
                "message": f"Security Patch: fix vulnerability in {vuln.file_path}",
                "content": new_content_encoded,
                "sha": file_sha,
                "branch": new_branch_name
            }
        )
        update_res.raise_for_status()
        
        # 6. Create a Pull Request
        pr_res = requests.post(
            f"{api_base}/pulls",
            headers=headers,
            json={
                "title": f"🔒 SentinelAI Security Patch: {vuln.rule_id}",
                "body": f"This is an automated security patch generated by SentinelAI.\n\n**Vulnerability:** {vuln.message}\n**Severity:** {vuln.severity}\n\nPlease review the changes before merging.",
                "head": new_branch_name,
                "base": default_branch
            }
        )
        if pr_res.status_code != 201 and "A pull request already exists" not in pr_res.text:
            pr_res.raise_for_status()
        
        # Mark as applied
        vuln.patch_status = 'applied'
        db.commit()

        pr_url = pr_res.json().get("html_url", "") if pr_res.status_code == 201 else ""

        return {
            "vuln_id": vuln_id,
            "status": "success",
            "message": "Patch applied and PR created successfully!",
            "pr_url": pr_url
        }
    except Exception as e:
        db.rollback()
        self.update_state(state='FAILURE', meta={'error': str(e)})
        raise e
    finally:
        db.close()
