"""add_api_keys_and_patch_fields

Revision ID: 490b379f9f3f
Revises: 0581089702af
Create Date: 2026-07-07 12:55:00.389192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '490b379f9f3f'
down_revision: Union[str, Sequence[str], None] = '0581089702af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('openai_api_key', sa.String(), nullable=True))
    op.add_column('vulnerabilities', sa.Column('ai_patch_code', sa.Text(), nullable=True))
    
    patchstatus = sa.Enum('PENDING', 'APPLIED', 'REJECTED', name='patchstatus')
    patchstatus.create(op.get_bind(), checkfirst=True)
    op.add_column('vulnerabilities', sa.Column('patch_status', patchstatus, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerabilities', 'patch_status')
    
    patchstatus = sa.Enum('PENDING', 'APPLIED', 'REJECTED', name='patchstatus')
    patchstatus.drop(op.get_bind(), checkfirst=True)
    
    op.drop_column('vulnerabilities', 'ai_patch_code')
    op.drop_column('users', 'openai_api_key')
    op.drop_column('users', 'github_token')
    # ### end Alembic commands ###
