FROM python:3.11-slim

WORKDIR /app

COPY apps/aipcsr-api/requirements.txt .
RUN apt-get update && apt-get install -y build-essential libpq-dev gcc && \
    pip install -U pip && \
    pip install --no-cache-dir -r requirements.txt

COPY apps/aipcsr-api/ .
COPY core/ /core

ENV PYTHONUNBUFFERED=1

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
