FROM python:3.11-slim

WORKDIR /app

COPY apps/aipcsr-worker/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY apps/aipcsr-worker/ .
COPY core/ /core

ENV PYTHONUNBUFFERED=1

CMD ["celery", "-A", "celery_app", "worker", "--loglevel=info", "-c", "4"]
